- name: Main Task | Installing and Configuring GitLab CE on RHEL/CentOS
  hosts: all
  vars_files:
    - vars/main.yml
  remote_user: ansible
  tasks: 
    - include: tasks/main.yml
  handlers:
    - include: handlers/main.yml
